### ISSUE TITLE
Implement Proper Unicode Handling

### ISSUE THREAD

**Issue by jasonuher** [rbavishi/Habitican-Curse#23]
From @LordVladneutral in #8 - Sometimes there are issues with symobls in task names - this should fail gracefully.

python2.7 habitican-curse :(
Traceback (most recent call last):
File "habitican-curse", line 54, in
curses.wrapper(main)
File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
return func(stdscr, *args, **kwds)
File "habitican-curse", line 39, in main
G.reqManager.FetchData()
File "/usr/lib/python2.7/site-packages/habitican_curse/request_manager.py", line 221, in FetchData
logger.debug("Processing a TODO: %s" % str(i['text']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 10: ordinal not in range(128)

**Comment by rbavishi** [comment]
Just to elaborate, this shouldn't fail for terminals with sufficient unicode support. The text just needs to be encoded before we do anything with it. This is fixed for now, but the encoding occurs at the places where it is actually used. Ideally, the encoding should be done as soon as the response arrives in order to prevent such errors at any use site.
